# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: ghcr.io/quarto-dev/quarto:1.4.550
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: quarto render
  deploy:
    docker:
      - image: ghcr.io/quarto-dev/quarto:1.4.550
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  example:
    jobs:
      - test
      - deploy:
          requires:
            - test
