name: Test and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test with Quarto
        run: |
          docker run -v ${{ github.workspace }}:/workspace ghcr.io/quarto-dev/quarto:1.4.550 quarto render /workspace

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Deploy only if pushing to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Quarto
        run: |
          docker run -v ${{ github.workspace }}:/workspace ghcr.io/quarto-dev/quarto:1.4.550 quarto render /workspace

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:Lexanomics/lexanomics.github.io.git
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: _site # The directory where your assets are generated
          SSH_PRIVATE_KEY: ${{ secrets.QUARTO_DEPLOY }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          TARGET_DIR: blog