name: Test and Deploy

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test with Quarto
        run: |
          docker run -v ${{ github.workspace }}:/workspace ghcr.io/quarto-dev/quarto:1.4.550 quarto render /workspace

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only if pushing to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'your-deploy-branch'  # Change this to your deployment branch name

      - name: Deploy with Quarto
        run: |
          docker run -v ${{ github.workspace }}:/workspace ghcr.io/quarto-dev/quarto:1.4.550 quarto render /workspace